### ISSUE TITLE
Native error handling upate

### ISSUE THREAD

**Issue by eglove** [Akronae/eslint-plugin-exception-handling#5]
I want to check if this plugin is still being updated. I think it's a great plugin, with a great idea.

"This means that built-in functions that might throw exceptions are not yet linted. I'm working on a feature for that..."

This would have to be a hardcoded list. I wrote a plugin rule of my own that does this, but it's very naive and incomplete. It's the first plugin I wrote and frankly I don't know what I'm doing. :)

https://github.com/eglove/eslint-plugin/blob/master/src/rules/handle-native-error.ts

I'm looking at return signatures with TS to make sure you can use things like lodash attempt() and my own attemptAsync().

Fail:

```ts
JSON.parse("")
fetch("")
```

Pass:

```ts
attempt(JSON.parse, "") // returns T | Error
attemptAsync(fetch, "") // returns Response | Error
```

And this is working on a very quick AI generated (but confirmed) list of JS methods that throw.

https://github.com/eglove/eslint-plugin/blob/master/src/util/native-throw-methods.ts

If this plugin is being updated, I'd like to know an update on your own implementation. I would love to start with an incomplete list and contribute.

**Comment by eglove** [comment]
Yeah,  that's a good idea. I think it would be OK to get an as exhaustive list as possible and bite the bullet on the fact that it may never be exhaustive.

I thought about looking at @types/node or TypeScript type definitions for vanilla globals and suggesting a PR for @throws comments. But you can effectively do this:

https://typescript-eslint.io/rules/no-deprecated/

I think it's largely the same problem. It's still a matter of finding what does and doesn't throw. I know this is something a lot of people want, so finding a way to properly warn people of throws would be huge. :)

**Comment by Akronae** [comment]
Hi @eglove,

Just layed out the foundations for native modules support in [v1.4.0](https://github.com/Akronae/eslint-plugin-exception-handling/releases/tag/1.4.0)
It's basically using [src/utils/native-throwing.ts](https://github.com/Akronae/eslint-plugin-exception-handling/blob/892f75230aecbd042def516e176cc1fd24d41c23/src/utils/native-throwing.ts)
Going to check how to analyze Node source code to build a complete list of functions that can throw.

Let me know if you have any thoughts.

![image](https://github.com/user-attachments/assets/de31a5ef-d1ac-4502-b426-f55c7e1d0a16)

**Comment by eglove** [comment]
Amazing! @Akronae 

May need to account for this style of ts parse options though:

eslint.config.js:

```ts
export default tseslint.config(...config, {
  languageOptions: {
    parserOptions: {
      project: true,
      tsconfigRootDir: "./tsconfig.json",
    },
  },
}
```

Error:

```sh
Error: ENOENT: no such file or directory, open 'C:\Users\glove\projects\project-builder\true'
Occurred while linting C:\Users\glove\projects\project-builder\src\build-project.ts:23
Rule: "exception-handling/no-unhandled"

Error: ENOENT: no such file or directory, open 'C:\Users\glove\projects\project-builder\true'
Occurred while linting C:\Users\glove\projects\project-builder\src\build-project.ts:23
Rule: "exception-handling/no-unhandled"
    at readFileSync (node:fs:448:20)
    at resolveTSAlias (file:///C:/Users/glove/projects/project-builder/node_modules/.pnpm/eslint-plugin-exception-handling@1.4.2_jiti@1.21.6_typescript@5.6.2/node_modules/eslint-plugin-exception-handling/dist/index.mjs:180:20)
    at getImportDeclaration (file:///C:/Users/glove/projects/project-builder/node_modules/.pnpm/eslint-plugin-exception-handling@1.4.2_jiti@1.21.6_typescript@5.6.2/node_modules/eslint-plugin-exception-handling/dist/index.mjs:205:12)
    at resolveImportedId (file:///C:/Users/glove/projects/project-builder/node_modules/.pnpm/eslint-plugin-exception-handling@1.4.2_jiti@1.21.6_typescript@5.6.2/node_modules/eslint-plugin-exception-handling/dist/index.mjs:264:15)
    at resolveId (file:///C:/Users/glove/projects/project-builder/node_modules/.pnpm/eslint-plugin-exception-handling@1.4.2_jiti@1.21.6_typescript@5.6.2/node_modules/eslint-plugin-exception-handling/dist/index.mjs:318:24)
    at resolveFunc (file:///C:/Users/glove/projects/project-builder/node_modules/.pnpm/eslint-plugin-exception-handling@1.4.2_jiti@1.21.6_typescript@5.6.2/node_modules/eslint-plugin-exception-handling/dist/index.mjs:327:20)
    at canFuncThrow (file:///C:/Users/glove/projects/project-builder/node_modules/.pnpm/eslint-plugin-exception-handling@1.4.2_jiti@1.21.6_typescript@5.6.2/node_modules/eslint-plugin-exception-handling/dist/index.mjs:402:15)
    at CallExpression (file:///C:/Users/glove/projects/project-builder/node_modules/.pnpm/eslint-plugin-exception-handling@1.4.2_jiti@1.21.6_typescript@5.6.2/node_modules/eslint-plugin-exception-handling/dist/index.mjs:378:24)
    at ruleErrorHandler (C:\Users\glove\projects\project-builder\node_modules\.pnpm\eslint@9.11.0_jiti@1.21.6\node_modules\eslint\lib\linter\linter.js:1084:48)
    at C:\Users\glove\projects\project-builder\node_modules\.pnpm\eslint@9.11.0_jiti@1.21.6\node_modules\eslint\lib\linter\safe-emitter.js:45:58
Process finished with exit code -1
```

Looks like this happens when trying to get tsconfig:

![2024-09-21 13_54_04-project-builder – C__Users_glove_projects_project-builder_node_modules_ pnpm_esl](https://github.com/user-attachments/assets/7b9ae059-8eb0-4320-9434-0eb55466a70d)

**Comment by Akronae** [comment]
Oh good catch, I improved this part that handles `parserOptions` certainly still not perfect, but it should work for you now on v1.4.3.

Concerning Node source code analysis I'm making progress should be coming soon.

**Comment by Akronae** [comment]
Hi @eglove,

99% of the native Node functions that throw should be correctly linted by the plugin by now :)
Closing this.

**Comment by eglove** [comment]
Hm, still not usable to me. Sorry for the lack of reply, I only see more errors the more I come back to this. Here’s what I have with a quick install.

This is still an **error** even though it’s caught:

```typescript
try {
  copyFileSync(...);
} catch (error: unknown) {
  globalThis.console.error(error);
}
```

This is **NOT** considered an error (note the difference is the error type is not declared as unknown, this is typically preferred over the default "any" because unknown must be narrowed in order to be used:

```typescript
  try {
    copyFileSync(...);
  } catch (error) {
    globalThis.console.error(error);
  }
```

Functional handling isn’t supported, this is an error:

```typescript
const attempt = (callback) => {
  try {
    return callback();
  } catch (error: unknown) {
    return new Error(error);
  }
}

const result = attempt(() => copyFileSync(...);
```

This does not show up as an error within the IDE:

```typescript
const test = import.meta.dirname;
```

But it does show up as an error on a CLI run:

```typescript
'import' might throw an exception and is not handled  exception-handling/no-unhandled
```

I think this needs a lot more testing and case handling.
